name: Deploy docs
on:
  push:
    branches:
      - master
  release:
    types:
      - published
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: |
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
      - run: npm ci
      - run: npm run docs:gh-pages
